### ISSUE TITLE
What's the difference between this and the other mindmap nextcloud app? Why are there two mind map apps?

### ISSUE THREAD

**Issue by jcklpe** [ACTom/files_mindmap#1]
Just curious. Seems there needs to be a better naming scheme in place to deal with this.

**Comment by jcklpe** [comment]
@ACTom  Cool. It might be a good idea to lay out explicitly in your app description what features you felt were lacking in the other and how yours addresses those things. 

Also it might help if you differentiate it with separate branding. I've actually got an ongoing project where I'm offering my services as a Designer for free to Open Source projects. If you'd like some help, just log an issue on this git repo and I'll get the process started :https://github.com/jcklpe/Open-Source-Branding

Also I know this is probably not that big a deal to you but it would still be fun for me to take a crack at it and would help add more energy to the NextCloud project as a whole! Let me know if you are interested 😄

**Comment by ACTom** [comment]
@jcklpe Good job.I'm having a headache for the design. But now I don't have any idea about the app's name or branding, when I think of it, I will send you an issue.

Thanks for your job.

**Comment by jcklpe** [comment]
@ACTom  No worries :) Also as a note, part of the great thing about getting a designer to help you with the name or branding is so you don't have to come up with it all by yourself. So even if you don't have any specific ideas on how you want to brand things, that's actually kind of the point of me putting up the project

**Comment by rubo77** [comment]
Call this app

> "Mind Map Files"

Because it is an extension to the files app
