### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by Chaleuri** [ACTom/files_mindmap#10]
I just installed the app and when i wanna open a file it only shows me a blank screen with an export thing and a close button on the top right corner. NC **14.0.3** on Ubuntu **18.04** App version: **0.0.9** Browser: **Opera**

**Comment by ACTom** [comment]
I don't have a test environment, but safari is the same. I guess the reason may be the same. The next version will be fixed. Please use chrome or firefox first, thank you!

**Comment by ACTom** [comment]
have a test, but now only support English.
