### ISSUE TITLE
Open Mindmap in sharedlink folder

### ISSUE THREAD

**Issue by skumpusch** [ACTom/files_mindmap#101]
Since update to 0.0.20 before i had 0.0.17 i get only MainTopic in Mindmap files if i open them from a sharedlink. Before the update this was not a problem. I would need this very urgent. Can i downgrade and still open the files or is there another solution?

Thanks

**Comment by ACTom** [comment]
You can try to uninstall this app,then unzip this file to app folder [https://github.com/ACTom/files_mindmap/releases/download/v0.0.17/files_mindmap-0.0.17.tar.gz], then enable this app.

I'll fix it in v0.0.21

**Comment by thawn** [comment]
FYI: For me this issue appears not only with .km files in folders but also for km. files themselves if they are shared via public link.
