### ISSUE TITLE
Xmind with modified title width failed to load

### ISSUE THREAD

**Issue by mamatt** [ACTom/files_mindmap#105]
Some xmind failed to load completely.  
In the Chrome console, you get an error which seems to belong to the kittycore js library :

```
Uncaught (in promise) TypeError: f.split is not a function
    at TextRenderer.update (kityminder.core.min.js?v=0.0.20:10)
    at Minder.renderNodeBatch (kityminder.core.min.js?v=0.0.20:10)
    at MinderNode.renderTree (kityminder.core.min.js?v=0.0.20:10)
    at Minder.refresh (kityminder.core.min.js?v=0.0.20:10)
    at Minder.importJson (kityminder.core.min.js?v=0.0.20:10)
    at viewer.js?v=0.0.20:200

```

After digging into those xmind, it seems that some of them have a svg:width:XXXpx in node title which lead to an split issue in the update function of kittycore.

Those svg are used when the user change the title size of an node !

I'll try to check where this can happen, but if you could help me where to find the xmind parsing, this should by nice ;)

Here is a zip with 2 files, quite the same but the non working one has a resized title :

[Download.zip](https://github.com/ACTom/files_mindmap/files/4402878/Download.zip)

**Comment by mamatt** [comment]
error seems to be in the xml transformation to json:

good one : `title: "subchild 1"`
bad one :` title: {0: "s", 1: "u", 2: "b", 3: "c", 4: "h", 5: "i", 6: "l", 7: "d", 8: " ", 9: "2", svg:width: "528", text: "subchild 2"}`

**Comment by mamatt** [comment]
If a node has an attribute :https://github.com/ACTom/files_mindmap/blob/1d381793f0c1a7e82c300dd3fea14a9af52234e5/js/mindmap.js#L580 

 text is casted as an object : https://github.com/ACTom/files_mindmap/blob/1d381793f0c1a7e82c300dd3fea14a9af52234e5/js/mindmap.js#L600

that what generate the bad json .

We need to handle those attribute correctly even if , we ignore then later.

I'll try to work on this in the next days, but @ACTom feel free to help ma as you certainly know your code better then I do

**Comment by ACTom** [comment]
Merged https://github.com/ACTom/files_mindmap/pull/106 to fix it.
