### ISSUE TITLE
Can't save from shared link - this.isSupportedMime is not a function

### ISSUE THREAD

**Issue by maurerle** [ACTom/files_mindmap#109]
I can't save a modified mindmap when edited from a shared link.
Reproduce:
1. create Mindmap file in Nextcloud
2. share Mindmap with a link
3. allow editing in link share menu
4. Edit from shared link and try to save

JS-Console shows: "this.isSupportedMime is not a function" mindmap.js:171:14
https://github.com/ACTom/files_mindmap/blob/cfe4e44fcd6f284180a59d9f4d3c923a8f7a8eeb/js/mindmap.js#L171

This can probably be enhanced to show a warning that saving is unavailable if the share does not allow editing.

**Comment by Michael2222** [comment]
Hello,
I have the same problem!
