### ISSUE TITLE
collaborate editing real time

### ISSUE THREAD

**Issue by sachinbanugariya** [ACTom/files_mindmap#113]
hello,
we have installed mindmap plugin, working good,
we have one question, can we able to edit mindmap file in real time collaborate way,
i.e two user can able to edit same file at a time. like onlyoffice give feature for excel.
let us know if we can able to do this.
thanks.

**Comment by ACTom** [comment]
This is difficult to do, onlyoffice has its own service, the file you edit is in its own service, and the file edited by our plugin is still in Nextcloud.
It is difficult at present, and it cannot be ruled out that it cannot be done in the future.
