### ISSUE TITLE
Set root topic to filename

### ISSUE THREAD

**Issue by CodeAlDente** [ACTom/files_mindmap#117]
Can we use the filename of the mindmap file for the root topic? I'm talking about the very first big blue bubble that comes up when you create a mindmap and start to work on it. This should only apply on creation with the ability for the users to change it to their liking.

![1589379474-001](https://user-images.githubusercontent.com/10899559/81824096-621b8f00-9535-11ea-88a9-76a7ce484a8b.png)

**Comment by ACTom** [comment]
No, now the file is first created and then edited, so the file name cannot be changed.

**Comment by CodeAlDente** [comment]
But that is perfect. We can use the filename to set the title of the mindmap.
