### ISSUE TITLE
Export does not work at all

### ISSUE THREAD

**Issue by eitzenbe** [ACTom/files_mindmap#121]
Nextcloud 18.0.6
MindMap 0.0.22

After upgrade to the new version exporting does not work at all.
No Error on JS Console, nothing in apache logs
Does export need php-imagick module?
(see https://bugs.launchpad.net/ubuntu/+source/php-imagick/+bug/1726432)

upgraded to php7.4 and isntall php-imagick, still export does nothing

Hmm weirdo seems to be related to chrome (settings?) in firefox export works

**Comment by ostasevych** [comment]
The same about Edge, which asks permission for pop-up and opens the blank page. Possibly, smth wrong with the processing of exporting and saving the file.

**Comment by BENETNATH** [comment]
Same here. would be great to be able to export, at least to the listed format. Additional like mm would also help^, to share with people that do not have access to nextcloud

**Comment by ostasevych** [comment]
> Same here. would be great to be able to export, at least to the listed format. Additional like mm would also help^, to share with people that do not have access to nextcloud

I tested, it works with Firefox. Probably, the issue with the Chromium engine...

**Comment by BENETNATH** [comment]
Edge behaves similarly, not sure if they already switched to chromium..?

**Comment by leonardoborlot** [comment]
Hi guys, here I have this problem too. 
There some one to take this jobs, may we sponsor it?

**Comment by MAXOUXAX** [comment]
This must absolutely be fixed, it's a huge problem when exporting the mindmap in PNG or Markdown format to use it elsewhere (in a powerpoint for example)

**Comment by leonardoborlot** [comment]
Hi guys. Theres any one if wanna to recive a bud to solve this feature? I wanna pay.

**Comment by ACTom** [comment]
Fixed.
