### ISSUE TITLE
integrity problem nextcloud 18.0.6 to 19.0 because of core/img/filetypes/mindmap.svg

### ISSUE THREAD

**Issue by devnull4242** [ACTom/files_mindmap#123]
While updating from Nextcloud 18.0.6 to 19.0 there is a integrity problem because of the file "core/img/filetypes/mindmap.svg.

We think the file "mindmap.svg" is copied to core/img/filetypes/mindmap.svg perhaps because of mimetypes, ... This might be ok or not. But with release upgrade there is in this case a problem with integrity check. I think because the normal core package does not include "mindmap.svg".

Thread in german, sorry

https://help.nextcloud.com/t/update-von-18-0-6-auf-19-0-0-probleme-mit-einer-datei-mindmap-svg/85276

**Comment by ACTom** [comment]
You can add [mindmap.svg](https://raw.githubusercontent.com/ACTom/files_mindmap/master/img/mindmap.svg) to core/img/filetypes/mindmap.svg manually.
