### ISSUE TITLE
Problem with mindmap.svg on nextcloud 19.0.3

### ISSUE THREAD

**Issue by MaxFlax** [ACTom/files_mindmap#129]
Nextcloud returns error on update to 19.0.3

Results
=======
- core
	- EXTRA_FILE
		- core/img/filetypes/mindmap.svg

Raw output
==========
Array
(
[core] => Array
    (
        [EXTRA_FILE] => Array
            (
                [core/img/filetypes/mindmap.svg] => Array
                    (
                        [expected] => 
                        [current] => b0484953431f937d2f10f8a8e526498763275691bda9252179c5b386ed94fbff95cc635022940b32f10c52afc15112774c158464b4853b4224ff9a7b8f650d0c
                    )

            )

    )

)

**Comment by ACTom** [comment]
You can delete this file to upgrade nextcloud.
Then reinstall this app.
