### ISSUE TITLE
Make 'saving file, file saved' for autosave take less attention.

### ISSUE THREAD

**Issue by jtagcat** [ACTom/files_mindmap#130]
Having a toast notification for 'Saving file...'; 'File saved!' every few seconds is distracting enough, that I blocked the notifications altogether.

I'd like to either opt out of the save notifications (failure saving should still arrive).

As an alternative, I'd suggest changing the save button to say 'Saving', and stay 'Saved', if no modifications is made. A bit similar to Google Drive.

**Comment by ACTom** [comment]
Good suggestion.
