### ISSUE TITLE
Compatibility with Nextcloud 20

### ISSUE THREAD

**Issue by welrbraga** [ACTom/files_mindmap#131]
Hi team. We should appreciate a compatibility with the new NC 20. Thanks for your good job till now!

**Comment by ChrWieg** [comment]
Yes please, we use the tool for a school class and would appreciate that too. Thank you very much for the great application.

**Comment by TheNomad11** [comment]
For me, this app works with NC 20. Just click on the "Enable untested app" button.

**Comment by ChrWieg** [comment]
Thanks for your hint, I will try this!

**Comment by ACTom** [comment]
Will fix it soon.

**Comment by ChrWieg** [comment]
> 
> 
> Hi team. We should appreciate a compatibility with the new NC 20. Thanks for your good job till now!

It works great, thanks a lot!

**Comment by ChrWieg** [comment]
Hi Team,
It is working perfectly with NC20, thanks a lot!
