### ISSUE TITLE
Toolbar problem

### ISSUE THREAD

**Issue by raffaelone** [ACTom/files_mindmap#132]
The toolbar using both Crome and Firefox hides the menu icons. The problem is only for the first tab. The others work properly.

Thank You

![toolbar](https://user-images.githubusercontent.com/73063127/99400839-c144cc80-28e7-11eb-851e-1ef91eb2d9fd.png)

**Comment by usefulnoise** [comment]
Some thing here :(

![Schermata 2021-01-12 alle 10 40 13](https://user-images.githubusercontent.com/4531535/104297304-01c55e80-54c3-11eb-9e49-e789b7ba5e8e.png)

**Comment by impronta48** [comment]
I confirm the problem is related to long translations of the words: Edit Node ->> Modifica Nodo (in italian) makes the menu wrap.
