### ISSUE TITLE
Again: non english strings

### ISSUE THREAD

**Issue by luntik2012** [ACTom/files_mindmap#15]
Please, remove all asian strings from tooltips, placeholders and all the rest

**Comment by ACTom** [comment]
When your Nextcloud is in English, they will all display English.

**Comment by luntik2012** [comment]
You are wrong. I hope you will not write such things again.

**Comment by luntik2012** [comment]
![image](https://user-images.githubusercontent.com/8270543/48508367-6e9b2a80-e85f-11e8-847d-0cde2b54448a.png)
I'm too lazy to screenshot tooltips

**Comment by ACTom** [comment]
Ok, because this is a Chinese project, the internationalization work has just begun. If there are any strings that have not been internationalized, please give me a screenshot, thank you!
After all, I usually use the Chinese interface.

**Comment by luntik2012** [comment]
isn't it better to translate from english to chinese to avoid such things instead?

**Comment by ACTom** [comment]
Because the core library was only used by the Chinese at the beginning, and there is no need for English, the international work is to start the nextcloud app.

**Comment by janLo** [comment]
Thank you for this great app!

I think, what @luntik2012 meant is the tooltips for the colors and the progress. I had a quick look for the progress and the strings come from the kityminder-editor project: https://github.com/fex-team/kityminder-editor/blob/13efd4cb98846cd556d7d63e60de8857fed90e5d/ui/directive/progressEditor/progressEditor.directive.js#L24-L28.

Is it possible to internationalize this project too? I've not enough time at the moment to work myself into this project to contribute the necessary code but would help with the translation process itself.

**Comment by janLo** [comment]
Oh, I just saw, that you already have a fork with internationalization support. So it might just be a bug. Things that I've found that re not translated are the colour and priority buttons in the idea panel and the color-picker for the font in the Appearance panel.
![screenshot_20181214_143816](https://user-images.githubusercontent.com/96146/50006615-97bdf080-ffae-11e8-82e3-a73f273dc2c0.png)
![screenshot_20181214_143804](https://user-images.githubusercontent.com/96146/50006616-98568700-ffae-11e8-88cf-7f51170bb66f.png)
![screenshot_20181214_143644](https://user-images.githubusercontent.com/96146/50006617-98568700-ffae-11e8-972f-fc1c15136ee5.png)

**Comment by dmbreakey** [comment]
The issue appears to trigger based on navigation choice:

- When creating a new node via the keyboard, the localized English string is used as the default name of the node.
- When creating a new node via the mouse, then the original Chinese string is used as the default name of the node.

Hope that helps identify the cause!

**Comment by ACTom** [comment]
@janLo @dmbreakey I see, it'll be fix in next version.

**Comment by janLo** [comment]
I found another palce: in the search:
![screenshot_20181229_225537](https://user-images.githubusercontent.com/96146/50542426-2ccf0500-0bbd-11e9-9667-f30a02d52142.png)

Thank you!

**Comment by luntik2012** [comment]
![image](https://user-images.githubusercontent.com/8270543/51108761-39ca3600-1804-11e9-955d-866ba78f916f.png)
![image](https://user-images.githubusercontent.com/8270543/51108795-4e0e3300-1804-11e9-88ed-652a23cbbdfc.png)
![image](https://user-images.githubusercontent.com/8270543/51108810-55cdd780-1804-11e9-9881-762753db6bfc.png)
![image](https://user-images.githubusercontent.com/8270543/51108824-5d8d7c00-1804-11e9-85f7-46ff448ef5fe.png)
![image](https://user-images.githubusercontent.com/8270543/51108834-64b48a00-1804-11e9-92cc-14ddd412b3e5.png)
![image](https://user-images.githubusercontent.com/8270543/51108859-7d24a480-1804-11e9-80dc-1192cac289a5.png)
![image](https://user-images.githubusercontent.com/8270543/51108893-9594bf00-1804-11e9-935b-6d3d02928431.png)
![image](https://user-images.githubusercontent.com/8270543/51108898-9b8aa000-1804-11e9-9670-55f1061eff19.png)
everything in chineese and not scalable (wrong sizes after translation)

**Comment by ngosang** [comment]
I support this issue. For non Chinese speakers this is killing the app.
In the future you could support more languages like Spanish, but IMHO, english support is essential.

**Comment by janLo** [comment]
I think the app made quite a good prigress in case of different languages since its introduction. @ngosang, you can easily add new translations (for spanish for example) yourself and provide it as a pull-request. This issue is more about some places where the translations are not yet in place.

**Comment by luntik2012** [comment]
it must be translation from english to chinese and others, not vice versa

**Comment by lachmanfrantisek** [comment]
> it must be translation from english to chinese and others, not vice versa

You probably not understand the author correctly. If I am not wrong, the app had been already there and it had been chinese-only for some time. The author then started to work on the app for a wider audience and released it to the Nextcloud app store. So, the translation needs to be done in the other way.

I would appreciate english/translations as well, but we need to bring only constructive feedback. This does not help anybody.

**Comment by luntik2012** [comment]
> So, the translation needs to be done in the other way.

No, it must be translated from english. It doesn't matter what was before it came to the nextcloud store.

**Comment by lachmanfrantisek** [comment]
> No, it must be translated from english. It doesn't matter what was before it came to the nextcloud store.

- If you mean, use english in code and translate to other language, than yes, I agree.
- If you mean, start the app development with english, then it's not posible, since there was no english at start and we can't change the history..;-)

But, let's focus on the current state -- Is there any missing text that needs to be made translatable?

Someone can create new (english) screenshots as well.

**Comment by cloud2018** [comment]
@lachmanfrantisek 
regarding the tooltips of the progress-icons:
In the file "files_mindmap/vendor/kityminder-editor/kityminder.editor.min.js" are some chinese words  (search for second occurrence of "getProgressTitle"):
e.getProgressTitle=function(e){switch(e){case 0:return"移除进度";case 1:return"未开始";case 9:return"全部完成";default:return"完成"+(e-1)+"/8"}}}}}])

These are displayed in chinese language independent, which language is set for nextcloud

**Comment by luntik2012** [comment]
sorry, removed this. it's too boring to write here about translation issues every time

**Comment by mamatt** [comment]
Just a summary of some of may PR to enhance l10n https://github.com/ACTom/files_mindmap/pull/39

With those every strings can be l10n. Also French translation is complete ;)
