### ISSUE TITLE
Support for NC 23

### ISSUE THREAD

**Issue by nursoda** [ACTom/files_mindmap#163]
Please officially test and release for NC 23 :) Thanks!

**Comment by nursoda** [comment]
Just tested it on NC 23.0.0 – seems to work fine without errors in /settings/admin/logging.

**Comment by Harfeur** [comment]
> Just tested it on NC 23.0.0 – seems to work fine without errors in /settings/admin/logging.

Maybe you can do a Pull request 🤷

**Comment by nursoda** [comment]
I won't since I did not check whether there are internal issues. I maintain my own NC app and know that pushing versions is little effort but seeing that 3 PR just sit there uncommented for months does not motivate me to create a fourth.

**Comment by LuCu11** [comment]
hey folks, have you get the app working in NC 23?

**Comment by nursoda** [comment]
As said on Dec, 7 the app does work fine in NC23. It just lacks the official build including that version. You may use "Enable untested app" to override this.

**Comment by ACTom** [comment]
Support in v0.0.26.
