### ISSUE TITLE
Mind map changes the content of core/js/mimetypelist.js

### ISSUE THREAD

**Issue by meinrecht** [ACTom/files_mindmap#168]
After an update of some apps inside Nextcloud, the overview page states:
"there is a security issue regarding invalid file hash".

This is caused by Mind map changing the above mentioned file. Here is the diff to the original version from `nextcloud`:
```
diff mimetypelist.js mimetypelist.js.new 
113,117c113
<     "application/vnd.xmind.workbook": "mindmap",
<     "image/targa": "image/tga",
<     "": "x-office/document",
<     "application/vnd.openxmlformats-officedocument.wordprocessingml.document.docxf": "x-office/document",
<     "application/vnd.openxmlformats-officedocument.wordprocessingml.document.oform": "x-office/document"
---
>     "application/vnd.xmind.workbook": "mindmap"
147a144
> 
```

See this discussion:
https://help.nextcloud.com/t/solved-invalid-hash-for-mimetypelist-js/40680/5
and this issue:
https://github.com/nextcloud/server/issues/26022

**Comment by ACTom** [comment]
Yes, there is no mindmap mimetype in the old version of nextcloud, so `core/js/mimetypelist.js` was modified during installation to support opening. This file will not be modified in versions after nc21.
