### ISSUE TITLE
Compatibility with upcoming NC 25

### ISSUE THREAD

**Issue by cetcondor** [ACTom/files_mindmap#176]
Just tested with Nextcloud 25 RC 3 and after re-activating the untested app, still .km files can't be opened anymore. The log files say "Error: Class "OCP\App" not found at <<closure>>" despite app being activated.

Please make the Mindmap app compatible with Nextcloud 25. Thanks for your work!

**Comment by mkrecek234** [comment]
Same here with released Nextcloud 25. Great app, would appreciate an update for NC 25 a lot @

**Comment by rogersbarn** [comment]
looking for the same. Love this mindmap app so much. Wish there would be a standalone version of it that can be run maybe in a docker container.

**Comment by msklywenn** [comment]
Bug can be fixed by changing files_mindmap/templates/viewer.php line 5 from 
```javascript
$version = \OCP\App::getAppVersion('files_mindmap');
```
to
```javascript
$version = \OC_App::getAppVersion('files_mindmap');
```

**Comment by Hoerli1337** [comment]
> Bug can be fixed by changing `files_mindmap/templates/viewer.php` line 5 from
> 
> ```js
> $version = \OCP\App::getAppVersion('files_mindmap');
> ```
> 
> to
> 
> ```js
> $version = \OC_App::getAppVersion('files_mindmap');
> ```
> 
> PR: #177

Works with nginx :)

**Comment by mn-web** [comment]
I first applied the fix and then also did the update. After these steps, I still have the same problem. I am getting an error message.

Error: Class "OCP\App" not found

**Comment by mn-web** [comment]
I did nothing, but in the meantime the app is working again. 🤔 The case is solved.
