### ISSUE TITLE
Mindmap app floods log files in NC26 due to deprecated /appinfo/app.php 

### ISSUE THREAD

**Issue by mkrecek234** [ACTom/files_mindmap#184]
Mindmap needs to refactor to IBoostrap for NC26, currently it throws this error once a second in the NC26 log file:
`/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.`

```
{"reqId":"qJAUrVRob5HGFSAkfzgS","level":0,"time":"2023-03-02T10:40:59+00:00","remoteAddr":"","user":"nxadmin","app":"files_mindmap","method":"GET","url":"/ocs/v2.php/apps/user_status/api/v1/statuses/admin","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Safari/605.1.15","version":"26.0.0.7","data":{"app":"files_mindmap"},"id":"64007d4d7c879"}
```

@ACTom Can this be fixed easily?

**Comment by nursoda** [comment]
Does 0.0.28 fix this, too!?

**Comment by eurodrew555** [comment]
Doesn't look fixed in 0.0.28, I'm still seeing this error in my debug logs

**Comment by mkrecek234** [comment]
> Does 0.0.28 fix this, too!?

No it does not fix this. Still one debug entry in NC's log per second triggered by mindmap...

**Comment by smarinier** [comment]
Hi @ACTom, i've got a commit moving from app.php to Application.php, so that this annoying warning is fixed. Woud you mind to accept me as contributor so that i can propose you a pull request ?

Note :One thing is that last version of files_mindmap would require now NC 20 with this fix.

**Comment by mkrecek234** [comment]
@smarinier Could you fork this repo, commit your change and then evebtually make a PR to merge from your forked repo in this one? Would be keen also to get the fix fast.

**Comment by smarinier** [comment]
> @smarinier Could you fork this repo, commit your change and then eventually make a PR to merge from your forked repo in this one? Would be keen also to get the fix fast.

Hi @mkrecek234 and @ACTom, as asked, i've forked and submitted my PR. You can have a look and even test it.
Yours,
