### ISSUE TITLE
Compatibility with NextCloud 26

### ISSUE THREAD

**Issue by JeremyCDP** [ACTom/files_mindmap#185]
[Mind Map ↗](https://apps.nextcloud.com/apps/files_mindmap) is declared as not compatible with Nextcloud 26.

Are there any plans to make it compatible? And if so, is there a visible deadline?

**Comment by hari-bo** [comment]
Project is dead?

**Comment by tjakober** [comment]
I activated it on my own risk, however it is working excellent on Nextcloud 26. I don't know why it should be incomatible.

**Comment by nursoda** [comment]
@ACTom Please bump info.xml to 27 and release a new version.

**Comment by ACTom** [comment]
Released.
