### ISSUE TITLE
Only a small part of the screen is used

### ISSUE THREAD

**Issue by jimbolaya** [ACTom/files_mindmap#19]
I'm running Nextcloud 14.0.4 and Mindmaps 0.1.0

As you can see from my picture, I can only see a small slice of the mindmap screen. I see this on Windows using both Iron (Chrome alternative) and using Firefox. I haven't yet tested this on Linux. Am I doing something fundamentally wrong?  

Maybe it's stuck in mobile mode? How would I "unstick" it from mobile mode?

![nextcloud_mindmap_screenshot](https://user-images.githubusercontent.com/3241087/50384661-f877b800-0695-11e9-8c16-cdc8e3661d5c.png)

**Comment by ACTom** [comment]
You need to report this in https://github.com/splitt3r/mindmaps
