### ISSUE TITLE
mindmap application does not seem to work in the current version of Nextcloud 28.0.2

### ISSUE THREAD

**Issue by wulfchr** [ACTom/files_mindmap#194]
Hello development team,

Unfortunately, the mindmap application does not seem to work in the current version of Nextcloud 28.0.2. 
No new maps can be created and no existing maps can be edited. Is there a way to install Mindmap locally on the PC, similar to DrawIO? 

best regards
wulfchr

**Comment by RTechSn** [comment]
I confirm.

**Comment by vdroners** [comment]
i confirm as well

**Comment by dualizeo** [comment]
I confirm, Solution is here by it has not be published officially
 https://help.nextcloud.com/t/nc28-mindmap-km-files-not-working/176809/11?u=ernolf

**Comment by wulfchr** [comment]
Besten Dank, Mindmap läuft wieder.

 

Gruß Wulf

 

Von: Dualizeo ***@***.***> 
Gesendet: Freitag, 16. Februar 2024 19:19
An: ACTom/files_mindmap ***@***.***>
Cc: wulfchr ***@***.***>; Author ***@***.***>
Betreff: Re: [ACTom/files_mindmap] mindmap application does not seem to work in the current version of Nextcloud 28.0.2 (Issue #194)

 

I confirm, Solution is here but it has not be published officially
https://help.nextcloud.com/t/nc28-mindmap-km-files-not-working/176809/11?u=ernolf

**Comment by grinapo** [comment]
See #191 and #190 ...

**Comment by Thatoo** [comment]
@wulfchr can you close your issue in favor of #191

**Comment by dualizeo** [comment]
I provided instructions for fix here https://github.com/ACTom/files_mindmap/issues/191#issuecomment-2091115022

**Comment by ACTom** [comment]
see https://github.com/ACTom/files_mindmap/issues/203
