### ISSUE TITLE
Update/Upgrgade to NC 29

### ISSUE THREAD

**Issue by toms1342** [ACTom/files_mindmap#198]
Please update this wonderful App to be used on 
NC Nextcloud Hub 8 (29.0.1)
and 
Nextcloud 29.0.2
This would be highly appreciated.

**Comment by admorgan** [comment]
I have started a fork that adds NC 29.  I am still investigating what is required to get it published to the appstore.

**Comment by Dylansob** [comment]
Fantastic.  I hope you are successful in getting it published in the app store.  I love using this app.  I'm running Nextcloud AIO via docker and I can't figure out how to manually add apps.

**Comment by JoannesSa** [comment]
Would be fine to get this app for NC 28.0.6 too.

**Comment by ernolf** [comment]
Look here: https://github.com/ACTom/files_mindmap/issues/197#issuecomment-2202831303

**Comment by JoannesSa** [comment]
Great, this is working fine.
Thanks a lot.

Von: Raphael Gradenwitz ***@***.***>
Gesendet: Dienstag, 2. Juli 2024 13:26
An: ACTom/files_mindmap ***@***.***>
Cc: Saurugg, Johannes ***@***.***>; Comment ***@***.***>
Betreff: Re: [ACTom/files_mindmap] Update/Upgrgade to NC 29 (Issue #198)


Look here: #197 (comment)<https://github.com/ACTom/files_mindmap/issues/197#issuecomment-2202831303>

**Comment by alfredhaslinger** [comment]
Hi,
would be fine to get i at Nextcloud 28.0.7 too ...

**Comment by ACTom** [comment]
see https://github.com/ACTom/files_mindmap/issues/203
