### ISSUE TITLE
Clarify licensing information

### ISSUE THREAD

**Issue by onny** [ACTom/files_mindmap#205]
Hey,

according to the LICENSE file in the project, it is licensed as AGPL3 https://github.com/ACTom/files_mindmap/blob/master/LICENSE

This file contains licensing info AGPL3+  https://github.com/ACTom/files_mindmap/blob/411db10d6f4bd325c56bd01dafca31fef4172d91/lib/Controller/PublicFileHandlingController.php#L7

I guess this is contradictory and should be fixed

Thank you!

**Comment by ACTom** [comment]
OK，I'll delete it in php file.
