### ISSUE TITLE
[Firefox] Export not working: Content-Security-Policy

### ISSUE THREAD

**Issue by filthycoding** [ACTom/files_mindmap#23]
Hello,

upon exporting a mindmap to svg format, the app apparently does nothing. Upon closer inspection however, my browser's JS console outputs this:

```
Content Security Policy: The page’s settings blocked the loading of a resource at data:image/svg+xml;base64,<redacted>… (“frame-src”).
```

Basically, the export is working, but all modern browsers block it.

Nextcloud allows apps using the AppFramework to add new types of content to the CSP as far as I know.

**Comment by filthycoding** [comment]
(same thing happens with png!)

**Comment by ACTom** [comment]
I guess you'are using firefox, try with chrome.
I'm finding how to fix it in firefox.

**Comment by filthycoding** [comment]
Indeed, it works in Chrome.

**Comment by ACTom** [comment]
duplicate with #27
