### ISSUE TITLE
Feature request: Collaborative editing (share link)

### ISSUE THREAD

**Issue by DoS007** [ACTom/files_mindmap#25]
Hi,

I really like this addon. But it would be even better, if you could collaborativly edit diagrams. 

Like this: You share a link with property editing allowed to someone. This one opens the link and now work on the diagram and even better could work collaborativly with you together.

?

**Comment by enca-pl** [comment]
Very good idea!

**Comment by tt33tt** [comment]
Great idea

**Comment by rmeichsner** [comment]
+1

some other apps like onlyoffice are currently able to be opened inside of shared links.

**Comment by ACTom** [comment]
I see, it will be supported in next version

**Comment by samir-s** [comment]
this addon as is is already excellent, one of the best I've ever seen, but with such a feature it would become awesome

**Comment by ACTom** [comment]
Added in v0.0.14.
