### ISSUE TITLE
[Firefox] Export feature not visible

### ISSUE THREAD

**Issue by ngosang** [ACTom/files_mindmap#27]
![imagen](https://user-images.githubusercontent.com/10577978/52913204-15a6bc80-32bc-11e9-952a-54ff42023bbb.png)

![imagen](https://user-images.githubusercontent.com/10577978/52913201-0cb5eb00-32bc-11e9-9d6d-11687932e814.png)

Mind Map: 0.0.11
Nextcloud: 15.0.4
Browser: Firefox 65

**Comment by OlliZabal** [comment]
I did a temporary quick and dirty fix in the file /templates/viewer.php by adding the following CSS code starting in line 100:
`        #export-button .dropdown-menu {
            left: -200%;
        }`
The problem for this is the absolute positioned #export-button element and the .dropdown-menu class is also positioned absolute by Bootstrap.

But there is still the Content Security Policy (CSP) issue with the export function in Firefox blocking this ;(. I guess the reason for this is the iframe solution from @ACTom and mybe some missing or wron ContentSecurityPolicy configuration. I'm trying to look deeper in this...

**Comment by mamatt** [comment]
Just for the record, i have push a PR (#6) which in addition to the french translation "enlarge" most of the CSS fields.

**Comment by ACTom** [comment]
Fix it, will publish in v0.0.12
