### ISSUE TITLE
[Firefox] Labels always show the scroll bars

### ISSUE THREAD

**Issue by ngosang** [ACTom/files_mindmap#28]
![imagen](https://user-images.githubusercontent.com/10577978/52913213-32db8b00-32bc-11e9-9262-6d1df218962e.png)

![imagen](https://user-images.githubusercontent.com/10577978/52913226-56063a80-32bc-11e9-8ca5-19bb7a101bb4.png)

Mind Map: 0.0.11
Nextcloud: 15.0.4
Browser: Firefox 65

**Comment by mamatt** [comment]
Just for the record, i have push a PR (https://github.com/ACTom/kityminder-editor/pull/6) which in addition to the french translation "enlarge" most of  the CSS fields.

**Comment by ACTom** [comment]
Fix in v0.0.13
