### ISSUE TITLE
Request: Mind Map icon for files

### ISSUE THREAD

**Issue by ngosang** [ACTom/files_mindmap#29]
Other file formats have icons. Even Draw.io
![imagen](https://user-images.githubusercontent.com/10577978/52913462-cc0ba100-32be-11e9-975e-f8dc3444cd74.png)

![imagen](https://user-images.githubusercontent.com/10577978/52913242-7cc47100-32bc-11e9-83f4-6a0bb99b245c.png)

Mind Map: 0.0.11
Nextcloud: 15.0.4
Browser: Firefox 65

**Comment by ACTom** [comment]
Added by https://github.com/ACTom/files_mindmap/commit/ad802f6186f9f531de927eb82f49818492e3dc10
