### ISSUE TITLE
Menu is too small in vertical size

### ISSUE THREAD

**Issue by bpcurse** [ACTom/files_mindmap#33]
The menu is partially cropped.  Should be a bit larger.

![bildschirmfoto_2019-02-21_17-20-58](https://user-images.githubusercontent.com/29312856/53184450-51fc5480-35fd-11e9-9867-e75a536e90ce.png)

Nextcloud 15.0.4, Mindmap 0.0.11

**Comment by OlliZabal** [comment]
The reason for this is a bit of "poor" CSS stuff in the /files_mindmap/vendor/kityminder-editor/kityminder.editor.min.css (which is actuallly not the business of @ACTom).

The [kityminder-editor](https://github.com/fex-team/kityminder-editor) was recently updated by @fex-team to V 1.0.67 but sadly not the CSS files.

With some little CSS changes this cosmetic stuff can be fixed quite fast.

Thanks to @ACTom for providing this for Nextcloud! Great tool with potential.

**Comment by bpcurse** [comment]
@OlliZabal Thank you for looking into this. Will try to fix it myself with this info.
And compliments to @ACTom for this great nextcloud app!

**Comment by OlliZabal** [comment]
@bpcurse if you use this only on a HD screen then you can do the following temporary fix by adding the CSS code to the file templates/viewer.php around line 100:
`        .append-group,
        .operation-group {
            width: auto;
        }
        .resource-editor .resource-dropdown .km-resource {
            overflow: auto;
        }`

**Comment by bpcurse** [comment]
@OlliZabal Thank you for saving me time :) Works as it should :+1: 
So as this is a problem in a another component, should I close this issue?

**Comment by OlliZabal** [comment]
I would keep it open and leave it up to @ACTom.

**Comment by mamatt** [comment]
Just for the record, i have push a PR (#6) which in addition to the french translation "enlarge" most of the CSS fields.

**Comment by ACTom** [comment]
Fixed it in v0.0.12

**Comment by bpcurse** [comment]
Looks like it got worse in 0.0.12, now it looks like this:
![Bildschirmfoto_2019-04-07_20-01-22](https://user-images.githubusercontent.com/29312856/55687721-75424f80-5970-11e9-86d0-9d374ac939af.png)
Accessed through Firefox 66.0.2

**Comment by mamatt** [comment]
It seem that the new German translation is using very long strings ....
Especially, for the up/down words ... 

Do you get the same if you switch to english ?

**Comment by bpcurse** [comment]
@mamatt After switching to english it's fine:
![Bildschirmfoto_2019-04-07_20-28-06](https://user-images.githubusercontent.com/29312856/55688014-1bdc1f80-5974-11e9-9e4b-e54256ecb323.png)
You are right, the new german translation didn't do any good ;)

**Comment by bpcurse** [comment]
This has been solved in 0.0.13. Thank you!

**Comment by christianlupus** [comment]
I have the same problem. However the mentioned fix in V0.0.13 does not help me, I get the following image when using German language:
![Screenshot_2019-07-03 tmp - Dateien - Nextcloud](https://user-images.githubusercontent.com/8202922/60604690-6ffe7080-9db8-11e9-9c1e-1a5706eae440.png)

The English language is all right. No problem then.
