### ISSUE TITLE
core/js/mimetypelist.js - integrity check

### ISSUE THREAD

**Issue by Pedulla** [ACTom/files_mindmap#38]
After installing this app causes core/js/mimetypelist.js to fail integrity check.

NC 15.05

**Comment by ACTom** [comment]
Yeah, install this app will change config/mimetypealiases.json and config/mimetypemapping.json then use occ maintenance:mimetype:update-js to update core/js/mimetypelist.js, so you can try run occ maintenance:mimetype:update-js again.

**Comment by ACTom** [comment]
v0.0.12 will not change this file.
