### ISSUE TITLE
Doesn't work with 14.0.3

### ISSUE THREAD

**Issue by crifalo** [ACTom/files_mindmap#4]
Hi,
it Doesn't work with 14.0.3.
Best regards
Laurent

**Comment by ACTom** [comment]
It works fine in my nc, what happen to you?

**Comment by crifalo** [comment]
I have white page 

Laurent GRINDLER   
	Phone: +33 6 78 31 44 37
Mobile: +41 79 963 33 01
Email: laurentgrindler@gmail.com
Skype: laurent.grindler

**Comment by ACTom** [comment]
@crifalo I have add your skype
