### ISSUE TITLE
screen resolution problem

### ISSUE THREAD

**Issue by Ruffunaru** [ACTom/files_mindmap#41]
Hello,

I updated MindMap from 0.0.11 to 0.0.12 with Nextcloud from 15.0.6 to 15.0.7 and the label tool disappeared.

![Screenshot_2019-04-09 Fichiers - Nextcloud](https://user-images.githubusercontent.com/31962405/55818145-3e964180-5af6-11e9-82c2-9092c0955092.png)

It is, in fact, a screen resolution problem because when I grow the navigator window up I can see the label tool.

![Screenshot_2019-04-09 Fichiers - Nextcloud(1)](https://user-images.githubusercontent.com/31962405/55818771-b2851980-5af7-11e9-8ea0-2e3b28ed8143.png)

I have a screen resolution of 1366x768.

**Comment by ACTom** [comment]
Fix in v0.0.13

**Comment by Ruffunaru** [comment]
Thank you, It works great :)
