### ISSUE TITLE
[Bug] Note urls point to prepended internal address

### ISSUE THREAD

**Issue by sunjam** [ACTom/files_mindmap#42]
Version 0.0.13 on Nextcloud 15.0.7

When adding a markdown note that reads: `[Test](www.example.com)`
The note link displayed in the mindmap will point to `[Test](https://domain.com/apps/files_mindmap/www.example.com)`

**Comment by ACTom** [comment]
Yes, you need to use [Test](http://www.example.com)

**Comment by sunjam** [comment]
Adding htttp or https will allow the url to function, but why not support arbitrary hyperlinks?  It confuses me as any url support is standard practice in markdown.

**Comment by ACTom** [comment]
You must specify the protocol, otherwise it will be relative to the current url according to the rules of the url. For detailed rules, please see https://github.github.com/gfm/#links
