### ISSUE TITLE
Compatibility with Owncloud

### ISSUE THREAD

**Issue by Baso123** [ACTom/files_mindmap#43]
Hi,

This addon for Nextcloud seems to be great !

Do you plan compatibility with Owncloud ?

Thks,
Rgds
Baso

**Comment by ACTom** [comment]
Because some of the APIs of Owncloud and Nextcloud are not compatible, there is currently no plan to adapt Owncloud.

**Comment by Baso123** [comment]
Thanks for the answer.

Rgds
Baso
