### ISSUE TITLE
Issue navigating MindMap due to incompatibility with Readme 1.0.2 

### ISSUE THREAD

**Issue by nguyenhung** [ACTom/files_mindmap#44]
System info:
- NextCloud version 15.0.7
- Mindmap version 0.0.13
- Readme version 1.0.2 https://apps.nextcloud.com/apps/files_readmemd
- Browser: Chrome and Safari on MacOS

How to replicate:
- Install Readme 1.0.2, create a HEADER.md with fairly complex syntax
- Create a MindMap.km in the same folder

Issue:
- Navigator is hard to locate and it's not working properly. The navigator can be found by scrolling the horizontal bar down to the very bottom. However none of the buttons are working properly.
- When a mind map is opened, the mind map is not centred. When it's in the centre, the toolbar is not visible

Workaround: 
- Move all MindMap into a blank folder

Reference:
https://gitlab.univ-nantes.fr/uncloud/files_readmemd/issues/10

![Scrolled to bottom](https://user-images.githubusercontent.com/1854253/56476079-f402b680-645f-11e9-9082-7cc1be4052c7.png)

![image](https://user-images.githubusercontent.com/1854253/56476102-70959500-6460-11e9-99ce-91db71633bb5.png)

**Comment by mamatt** [comment]
Fix in commit : [58e29c59](https://gitlab.univ-nantes.fr/uncloud/files_readmemd/commit/58e29c594389d01fda4feee81ebf770ead469134  )

A new version has been published !

**Comment by nguyenhung** [comment]
Thank you @mamatt
