### ISSUE TITLE
Save button

### ISSUE THREAD

**Issue by Ravinou** [ACTom/files_mindmap#56]
Hi, and thank you for this great work ! Very useful !

Is it possible to add a "save" button. I often close my document too quickly and lose my changes :(
The indication that the document was saved is also very fast and we do not always see it, we do not know if we can close the document or if we still have to wait ... It's even more problematic when we are on bad internet connection.

Thank you !!
Best regards

**Comment by ACTom** [comment]
Hello,
You can try the last commit manual.

**Comment by Ravinou** [comment]
Thank you so much !! <3

**Comment by Ravinou** [comment]
save button is working.
Thanks again
