### ISSUE TITLE
.mm files

### ISSUE THREAD

**Issue by kozliatko** [ACTom/files_mindmap#6]
It is possible to edit .mm files exported from other MindMap sw?

**Comment by ACTom** [comment]
Yeah, I'm work for support multi-canvis in a file now,after this to support to edit Xmind files and FreeMind files.

**Comment by gbarre** [comment]
This feature would be really great!

**Comment by beccon4** [comment]
It would improve usability a lot if we were able to at least import our Freemind/Freeplane Files - even if it were data and structure only (leaving out the format)

**Comment by cfsancas** [comment]
It could be a great feature. also import from markdown files.

**Comment by ACTom** [comment]
Added by https://github.com/ACTom/files_mindmap/commit/8def1a89e3eff7befac650ca36594803d33289be https://github.com/ACTom/files_mindmap/commit/dc68a2408e62f09c85ddb33a00ec5a40d1e9aefb
