### ISSUE TITLE
Export (not working in firefox q) (working in chromium)

### ISSUE THREAD

**Issue by xelcho** [ACTom/files_mindmap#62]
NC: 14.0.13
Mind Map .0.0.15
Firefox Quantum (fails)
Chromium Version 76.0.3809.100 (Official Build) (64-bit) (works as expected)

On click Export opens to reveal the file types. When selecting the file types the cursor changes to the "I" beam and on selection of file type does nothing.

**Comment by ACTom** [comment]
Do you still have this problem?

**Comment by xelcho** [comment]
@ACTom Thanks for asking. I have not tested it in a while, and your prompting made me do so. I am happy to report it is working as expected. Thank you!!!
