### ISSUE TITLE
PHP Fatal error while activating app

### ISSUE THREAD

**Issue by Django-BOfH** [ACTom/files_mindmap#73]
While trying to activate files_mindmap this error occurs: 

sudo -u apache php /srv/www/html/cloud/occ app:enable files_mindmap
PHP Fatal error:  Declaration of Symfony\Component\Console\Output\NullOutput::write($messages, bool $newline = false, int $options = self::OUTPUT_NORMAL) must be compatible with Symfony\Component\Console\Output\OutputInterface::write($messages, $newline = false, $options = 0) in /srv/www/html/cloud/apps/news/vendor/symfony/console/Output/NullOutput.php on line 25

CentOS Linux release 7.7.1908 (Core)
PHP 7.3.13 (cli) (built: Dec 19 2019 03:21:53) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.13, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.13, Copyright (c) 1999-2018, by Zend Technologies

**Comment by ACTom** [comment]
No reproduce, you can try 
`composer update`

**Comment by maurerle** [comment]
This is the same error as in #78 and only appears if the NC News app is installed too. Would be great to fix it as the current workaround is not intuitive for the majority.

**Comment by ACTom** [comment]
This is a bug with news app, waiting for the next version of news.
You can try to disable news app, then install this app, finally re-enable news app.

**Comment by ACTom** [comment]
After testing found a class that can not cause conflicts, fixed this problem.
https://github.com/ACTom/files_mindmap/commit/f906989139682955c42606e3c1b020b1ef5ee334
