### ISSUE TITLE
Compatibility with NextCloud 18

### ISSUE THREAD

**Issue by admorgan** [ACTom/files_mindmap#74]
I have not tested with 18, but the app is listed as only being tested up to 17 and therefore gives a scary warning.

**Comment by granfot** [comment]
I didn't think to check before I upgraded NextCloud to v.18 and MindMaps was my most common use for it. I love it and I really do miss it.

**Comment by Tsunami2056** [comment]
Hello, I also miss this app since I moved to Nextcloud 18. When I try to update it it mentions:
"Certificate "4349" has been revoked"

Don't know if that helps.

**Comment by SystemKeeper** [comment]
> "Certificate "4349" has been revoked"

I've seen this as well, but with a different mindMap app than this. You sure you're trying to install this one?

Other than that, enabling this app here in NC18 works for me, but breaks the activity-app. Maybe someone can have a look?

**Comment by admorgan** [comment]
I get the following errors when trying to re-enable it on NC18 
```
[index] Error: Exception: Return value of "OC\Core\Command\Maintenance\Mimetype\UpdateJS::execute()" must be of the type int, NULL returned. at <<closure>>
```
```
[PHP] Error: file_put_contents(/var/www/nextcloud.morgancomputers.net/htdocs/nextcloud/core/js/mimetypelist.js): failed to open stream: Permission denied at /var/www/nextcloud.morgancomputers.net/htdocs/nextcloud/core/Command/Maintenance/Mimetype/UpdateJS.php#57

POST /settings/apps/enable
from 204.77.163.109 by admorgan at 2020-01-29T17:38:52+00:00
```

**Comment by Tsunami2056** [comment]
> 
> 
> > "Certificate "4349" has been revoked"
> 
> I've seen this as well, but with a different mindMap app than this. You sure you're trying to install this one?
> 
> Other than that, enabling this app here in NC18 works for me, but breaks the activity-app. Maybe someone can have a look?

I was indeed trying with this same app. For some reason, I've been able to get it to work now. I'll let you know if I have an issue with the activity app.
Cheers

**Comment by ACTom** [comment]
> 
> 
> I get the following errors when trying to re-enable it on NC18
> 
> ```
> [index] Error: Exception: Return value of "OC\Core\Command\Maintenance\Mimetype\UpdateJS::execute()" must be of the type int, NULL returned. at <<closure>>
> ```
> 
> ```
> [PHP] Error: file_put_contents(/var/www/nextcloud.morgancomputers.net/htdocs/nextcloud/core/js/mimetypelist.js): failed to open stream: Permission denied at /var/www/nextcloud.morgancomputers.net/htdocs/nextcloud/core/Command/Maintenance/Mimetype/UpdateJS.php#57
> 
> POST /settings/apps/enable
> from 204.77.163.109 by admorgan at 2020-01-29T17:38:52+00:00
> ```

You should give file (/var/www/nextcloud.morgancomputers.net/htdocs/nextcloud/core/js/mimetypelist.js) write premission, this app need to update this file to support open .km file.

**Comment by ACTom** [comment]
Now release v0.0.16 to support NC 18 and 19.
