### ISSUE TITLE
Conflict with News app

### ISSUE THREAD

**Issue by GNeerings** [ACTom/files_mindmap#78]
I encountered the following error while trying to install the .17 version of Mind Map using the OCC app:install command. 

PHP Fatal error:  Declaration of Symfony\Component\Console\Output\NullOutput::write($messages, bool $newline = false, int $options = self::OUTPUT_NORMAL) must be compatible with Symfony\Component\Console\Output\OutputInterface::write($messages, $newline = false, $options = 0) in /var/www/html/custom_apps/news/vendor/symfony/console/Output/NullOutput.php on line 25

I uninstalled the News app and re-installed the Mind Map app. Once it was enabled, I reinstalled the News app and both apps appear to be working correctly.

**Comment by paulcalabro** [comment]
@GNeerings Thanks! That worked for me, though I just disabled and re-enabled the apps in that sequence.

**Comment by ACTom** [comment]
Duplicate with #73
