### ISSUE TITLE
MindMap filename in title

### ISSUE THREAD

**Issue by maurerle** [ACTom/files_mindmap#80]
If you open a mindmap file the Title in the browser tab stays "Files - Nextcloud" which does not allow you to see that there is a Mindmap file open and which mindmap file is open.

It would be good if the title contains the Mindmap filename in the HTML title for a better multi-tab experience.
Collabora Office for example just writes the Filename into the header so "Document.odt - Files - Nextcloud"

Great App! I like it.

**Comment by ACTom** [comment]
Added in v0.0.18
