### ISSUE TITLE
ugh I just lost all my work

### ISSUE THREAD

**Issue by zeroepix** [ACTom/files_mindmap#85]
I spent 3 hours creating a mind map. The tool was fine and useable. I clicked "save", it didn't really say anything so I assumed it had. Then I clicked the x to exit and it gave me an alert:

Unsaved File
! The file has not been saved. Is it saved?

<no>  <yes>

What on earth does this even mean? At this point, neither YES nor NO seemed to do anything, and all I could do was click 'x', which just removed the alert. Needless to say, I clicked the file and all my work was gone. This is insanely broken.

I created the file by clicking the "+" in a files folder -> new mindmap file.

**Comment by zeroepix** [comment]
Extra info...Javascript was complaining in the background the whole time:

Uncaught TypeError: window.parent.OCA.FilesMindMap.showMessage is not a function
    at Object.showMessage (viewer.js?v=0.0.17:109)
    at Object.setStatusMessage (viewer.js?v=0.0.17:119)
    at Object.save (viewer.js?v=0.0.17:128)
    at viewer.js?v=0.0.17:172
    at Object.<anonymous> (mindmap.js:154)
    at u (main.js:25)
    at Object.fireWith [as resolveWith] (main.js:25)
    at k (main.js:25)
    at XMLHttpRequest.<anonymous> (main.js:25)

**Comment by ACTom** [comment]
This looks like the app is not loading, try reinstalling the app.

**Comment by sgallant04** [comment]
anyway to re-enable auto save?   I just lost a lot of work ....w/o autosave this may be a dealbreaker for me.

**Comment by ACTom** [comment]
This app is set to save in 5 seconds, I cannot reproduce your problem.

**Comment by sgallant04** [comment]
Hmmm what I'm I missing I recently updated this app and now it has a "SAVE" button up in the upper right hand Conner where previously it was all auto save.  Now If I don't specifically the the "SAVE" button all my work is lost.   After your previous comment I made a new mind map and reproduced the lost work again.

**Comment by zeroepix** [comment]
Ok I second the urgency on the auto-save feature...I accidentally pressed alt-left and the browser went back to the previous page. The last save I had was 25 minutes prior, and I'd added a lot of stuff I don't want to add again.

The app should really save on every change.

**Comment by sgallant04** [comment]
Is this being left broken?

**Comment by CaroZeroWaste** [comment]
I lost several hours, too! The problem is still existing.

**Comment by ACTom** [comment]
Can you tell me which version of Nextcloud do you use? @zeroepix @CaroZeroWaste @sgallant04

**Comment by sgallant04** [comment]
Nextcloud current version 18.01 update channel "stable"

**Comment by zeroepix** [comment]
NextCloud 17.0.1 for me, stable channel.

**Comment by zeroepix** [comment]
The problem hasn't happened to me again since that first time, although it does seem to be happening to others randomly. I have been saving every few seconds manually just in case. It does go silent sometimes when I click save and next time that happens I'll try and capture a console output. 

An autosave / js alert when it can't connect would be a good way for people to take alternative action (e.g. export the pic).

**Comment by CaroZeroWaste** [comment]
@ACTom I Use Version Nextcloud 17.0.3 and Mindmap 0.0.17.
The problem is still there.

Autosave works fine in Nextcloud Version 16.0.1 with Mindmap 0.0.13...

**Comment by jtagcat** [comment]
MM 0.0.17
Nextcloud 18.0.1

Autosave does not work anymore. (last time working, checked about a month ago)

**Comment by ACTom** [comment]
Next release will add autosave.

**Comment by ACTom** [comment]
Added in v0.0.18
