### ISSUE TITLE
Not installing on Nextcloud v18.0.1

### ISSUE THREAD

**Issue by fvzwieten** [ACTom/files_mindmap#88]
[index] Error: Exception: Return value of "OC\Core\Command\Maintenance\Mimetype\UpdateJS::execute()" must be of the type int, NULL returned. at <<closure>>

0. /srv/http/nextcloud/lib/private/AppFramework/App.php line 125
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings\Con ... {}, "enableApps")
1. /srv/http/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\Settings\\ ... r", "enableApps", OC\AppFramework\ ... {}, {_route: "settin ... "})
2. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "settin ... "})
3. /srv/http/nextcloud/lib/private/Route/Router.php line 299
   call_user_func(OC\AppFramework\ ... {}, {_route: "settin ... "})
4. /srv/http/nextcloud/lib/base.php line 1008
   OC\Route\Router->match("/settings/apps/enable")
5. /srv/http/nextcloud/index.php line 38
   OC::handleRequest()

POST /settings/apps/enable
from 62.251.126.117 by fred at 2020-02-15T10:33:35+00:00

**Comment by john-2000** [comment]
I have the same error, any ideas how to fix

**Comment by ACTom** [comment]
Duplicate with #73
