### ISSUE TITLE
No autosave anymore!!??? Just lost the work of many hours!!

### ISSUE THREAD

**Issue by CaroZeroWaste** [ACTom/files_mindmap#90]
We were used to a working autosave funktion. Now we have lost several hours in diferent projects/files within the whole team!!!! I only just noticed by coincidence.

When such an importand feature is changed with an update, there should be an emphasized message or warning!

Why has it been changed at all????????????? Can you please revert it?

I am constantly fighting for opensource and against the implementation of any google feature in my team. This is going to weaken my position in those discussions considerably :-(

**Comment by ACTom** [comment]
duplicate to #85
