### ISSUE TITLE
Issue in css Frame

### ISSUE THREAD

**Issue by alessandropaglierani** [ACTom/files_mindmap#91]
![mindmap-issue](https://user-images.githubusercontent.com/22717704/75634592-7d9e1b80-5c0f-11ea-9178-2ae528b7adbb.png)
Hi, first of all, great job.
I'd like to report that, at least on firefox, as you can see in attached screenshot, the main tool bar is not displayed correctly.
Other tabs in toolbar are fine, but not the main one.
(in my case setting in .minder-editor top:120px fixes the issue)
Waiting for updates!
Thanks!

**Comment by ACTom** [comment]
The reason for this is that the internationalized translation strings are too long. Can you go to https://github.com/ACTom/kityminder-editor to shorten the related strings?

**Comment by alessandropaglierani** [comment]
Hmm... i've taken a look at the translated strings, and unfortunately italian is a language with some pretty long words that, when shortened, can be hard to understand, because the root of the word can then have multiple meanings.
Maybe i could try thinking of synonyms that could be shorter.
So, given that the issue is addressed, i'm closing
Thanks!
