### ISSUE TITLE
SyntaxError: JSON.parse: unexpected end of data at line 1 column 2 of the JSON data

### ISSUE THREAD

**Issue by SwoosOfficial** [ACTom/files_mindmap#94]
When creating a new km. 

However when i rename it to .md it opens. 
But neither saving nor reopening works. Obviously some File i/O Problem, but all acess rights are well working with all other apps (eg markdown editor)

Server: 

Nextcloud v18.0.0
OS: Raspian
Hardware: Raspberry Pi 4

Client:

Firefox 74.0 & Chromium 80.0
Ubuntu 19.10

**Comment by SwoosOfficial** [comment]
P.S.: Syslog, phpfpm_log and Protocol empty.

**Comment by t-markmann** [comment]
This happens to me as well on NC 17.0.3

Workaround: take an old, empty .mk file. The app seems to create the new files from a defective template.

**Comment by vasyugan** [comment]
> This happens to me as well on NC 17.0.3
> 
> Workaround: take an old, empty .mk file. The app seems to create the new files from a defective template.

Where do I get one?

**Comment by t-markmann** [comment]
Try this one: [mindmap.zip](https://github.com/ACTom/files_mindmap/files/4332825/mindmap.zip)

**Comment by SwoosOfficial** [comment]
Do you know the folder where the template lies. Then i just replace the template file. 🤔

**Comment by SwoosOfficial** [comment]
> Try this one: [mindmap.zip](https://github.com/ACTom/files_mindmap/files/4332825/mindmap.zip)

Workaround work for a single file! Thanks.

**Comment by ACTom** [comment]
Oh! This is a bug caused by the introduction of a new supported format. I have not tested the newly created file before, and I will fix it now.

**Comment by ACTom** [comment]
Fixed in v0.0.20
