### ISSUE TITLE
v20 considers v18 mindmaps as corrupt 

### ISSUE THREAD

**Issue by jonhind** [ACTom/files_mindmap#97]
That's all I Can say - here's a (zipped) 
[Luton.km.zip](https://github.com/ACTom/files_mindmap/files/4339979/Luton.km.zip)
file that is considered corrupt:

**Comment by ACTom** [comment]
![export](https://user-images.githubusercontent.com/6156919/76888492-f7483180-68be-11ea-9551-fa7b15bdeaee.png)
This is the effect I opened with V0.0.20, is it correct?

**Comment by jonhind** [comment]
Yes it is. 
I re-opened it and it works fine now - not sure why.
Sorry to have wasted your time.
